### PR TITLE
Revert "Initial commit to set up the repo"

### PR DESCRIPTION
**Pull request by psarvesh**
Reverts vido4790/mohari_task_tracker#1

### CODE REVIEW

**Comment by psarvesh** [comment]
Reverted, because we can have 2/3 more directories. Bin/ Lib/ and Doc/ for binary, libraries and documentation. And the tasks.txt can move into the Doc directory.

**Comment by vido4790** [comment]
Can we instead have a single pull request that incorporates adding these files in their respective directories too? Also consider adding a Tests/ folder which can be empty for now, but can later include any tests we need. Also we can have such that one of the files have a version number in them, and whenever we merge a pull request we update the version number and tag the trunk. 

https://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by psarvesh** [comment]
Agreed. I will add a Test/ folder as well. I can continue this on your branch eng/init_uvido4790

**Comment by psarvesh** [comment]
revert-1-eng/init_u-vido4790 can be deleted

**Comment by vido4790** [comment]
@psarvesh, the general git courtesy suggests that the requester of the merge should be the one deleting or merging the branch.

**Comment by vido4790** [comment]
What do you think about Tools/ folder @psarvesh?

**Comment by psarvesh** [comment]
Yes. A tools folder will be good as well. Let's add that too. I will close this pull request and delete that branch. @vido4790 you add these suggestions and make a pull request. I will be more careful

**Pull request closed without merging**
